.build-template:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/$CI_PROJECT_PATH_SLUG:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID .
    - docker push ${CI_REGISTRY_IMAGE}/$CI_PROJECT_PATH_SLUG:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
